version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: unless-stopped
    network_mode: host
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://127.0.0.1:27017/tracking_bot
      - PORT=4000
      - BOT_TOKEN=${BOT_TOKEN}
      - DEV_AUTH=${DEV_AUTH}
      - PUBLIC_URL=${PUBLIC_URL}